### ISSUE TITLE
Make a release with Julia 1.0 compatibility

### ISSUE THREAD

**Issue by ianfiske** [rdeits/ConditionalJuMP.jl#47]
Now that we have merged Julia 1.0 compatibility into master, are there any outstanding items that prevent a release?  Installation of this package under Julia 1.0 has a bit of extra friction until such a release is made.  Thanks!

**Comment by rdeits** [comment]
Good point! Done: https://github.com/rdeits/ConditionalJuMP.jl/releases/tag/v0.1.0

**Comment by rdeits** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/21254

**Comment by ianfiske** [comment]
Great, thank you!

**Comment by pdelfino** [comment]
Hi, 
I am using Julia Version 1.1.0 (2019-01-21).  I am also using JuMP v0.19.0.

When I try to run `import Pkg; Pkg.add("ConditionalJuMP")` I receive this error message:

```
ERROR: Unsatisfiable requirements detected for package ConditionalJuMP [ae04f764]:
 ConditionalJuMP [ae04f764] log:
 ├─possible versions are: [0.0.1-0.0.5, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.5, 0.1.0]
 └─restricted by compatibility requirements with JuMP [4076af6c] to versions: uninstalled — no versions left
   └─JuMP [4076af6c] log:
     ├─possible versions are: [0.1.1-0.1.2, 0.2.0, 0.3.0-0.3.2, 0.4.0-0.4.1, 0.5.0-0.5.8, 0.6.0-0.6.3, 0.7.0-0.7.4, 0.8.0, 0.9.0-0.9.3, 0.10.0-0.10.3, 0.11.0-0.11.3, 0.12.0-0.12.2, 0.13.0-0.13.2, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0-0.16.2, 0.17.0-0.17.1, 0.18.0-0.18.5, 0.19.0] or uninstalled
     └─restricted to versions 0.19.0 by an explicit requirement, leaving only versions 0.19.0
```

Is this happening because your package only supports Julia's version 1.0?

Sorry if this is a silly question. I am new to the Julia ecossystem and I often have problems with packages in different programming languages.

Sorry if this is an improper place to ask this question. I couldn't think of a better public place to ask this. I thought it would be better than opening a new issue or sending a private email (other people wouldn't see the answer).

Btw, congratulations for the work. I only read the README, but this looks like great work.

Thanks in advance.

**Comment by ianfiske** [comment]
@pdelfino This is happening because of your explicit restriction to use JuMP 0.19.0, but ConditionalJuMP is restricted to versions less than 0.19.0.

**Comment by jrock2468** [comment]
I think this becomes confusing because using Julia 1.0 implies that you are using JuMP 0.19.0 per JuMP's requirements.  

I don't think you can currently use ConditionalJuMP with Julia 1.0 since it isn't compatible with JuMP 0.19.0 yet.  @ianfiske, if I'm missing something, please correct me.

**Comment by ianfiske** [comment]
> Julia 1.0 implies that you are using JuMP 0.19.0 per JuMP's requirements

This isn't true.  I'm still using 0.18.5 with Julia 1.1.  And ConditionalJuMP is also working with 1.0+.  You just need to stick with the 0.18 branch until all your needed JuMP-extensions are 0.19 compatible.

@jrock2468 Try pinning your JuMP version to 0.18.5.

**Comment by jrock2468** [comment]
> > Julia 1.0 implies that you are using JuMP 0.19.0 per JuMP's requirements
> 
> This isn't true. I'm still using 0.18.5 with Julia 1.1. And ConditionalJuMP is also working with 1.0+. You just need to stick with the 0.18 branch until all your needed JuMP-extensions are 0.19 compatible.
> 
> @jrock2468 Try pinning your JuMP version to 0.18.5.

This combo worked for me.  I misunderstood the exclusive boundary of Julia REQUIREMENTS files.  Thanks for the reply, @ianfiske .
